# This workflow creates all environment-specific resources that are shared across applications.
# This needs to run before creating an application-specific environment.
name: 02 - Manually create a shared environment

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create.'
        required: true
        default: 'staging'
jobs:
  deploy-network-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: Deploy the network stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: NPM install
        run: cd cdk && npm install

      - name: Deploy network stack

        run: |
          cd cdk
          npm run network:deploy --  -c accountId=${AWS_ACCOUNT_ID} -c region=${AWS_DEFAULT_REGION} -c environmentName=${{ github.event.inputs.environmentName }}