name: deploy aws application

on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: "The docker image to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy AWS TEST application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: NPM install
        run: cd cdk && npm install

      - name: Deploy service stack
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run service:deploy \
          -- -c environmentName=staging \
          -- -c applicationName=test-aws \
          -- -c dockerImageTag=${{ github.event.inputs.docker-image-tag }} \
          -- -c dockerImageUrl=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/aws-test:latest
