# This workflow deploys all resources that are specific to the Todo-App, but not the app itself.
name:  Update the aws-test environment in staging

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  push:
    paths:
      - 'cdk/**/*DeploymentSequencer*'
      - 'cdk/pom.xml'
      - 'cdk/**/*Cognito*'
  workflow_dispatch:
jobs:
  deploy-cognito-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: Deploy the Cognito stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy Cognito stack
        working-directory: cdk
        run: npm run cognito:deploy

  deploy-sequencer-lambda:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: Deploy the Deployment Sequencer stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: NPM install CDK dependencies
        working-directory: cdk
        run: npm install

      - name: NPM install Deployment Sequencer dependencies
        working-directory: cdk/deployment-sequencer-lambda
        run: npm install

      - name: Build Deployment Sequencer
        working-directory: cdk/deployment-sequencer-lambda
        run: npm run dist

      - name: Deploy Deployment Sequencer
        working-directory: cdk
        run: npm run deployment-sequencer:deploy -- -c applicationName=aws-test -c githubToken=${{ secrets.GH_API_TOKEN }}
