# This workflow deploys all resources that are specific to the Todo-App, but not the app itself.
name:  Update the Todo-App environment in staging

on:
  push:
    paths:
      - 'cdk/**/*DeploymentSequencer*'
      - 'cdk/pom.xml'
  workflow_dispatch:
jobs:
  deploy-sequencer-lambda:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: Deploy the Deployment Sequencer stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: NPM install
        run: cd cdk && npm install

      - name: Deploy Deployment Sequencer
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          cd deployment-sequencer-lambda
          npm install
          npm run dist
          cd ..
          npm run deployment-sequencer:deploy -- -c applicationName=aws-test -c githubToken=${{ secrets.GH_API_TOKEN }}  -c accountId=${AWS_ACCOUNT_ID} -- -c region=${AWS_DEFAULT_REGION}
